[package]
name = "rekv"
version = "0.0.2"
authors = ["atduyar"]
edition = "2024"
repository = "https://github.com/atduyar/rekv"
description = """
An experimanntal redis like Key-Value-Store client and server.
"""
license = "MIT"

[dependencies]
smol = "2.0.2"
